env: "local" # local, dev, prod
storage_path: "C:/Users/dshum/GolandProjects/url-shortener/storage/storage.db"
http_server:
  address: "localhost:8082"
  timeout: 4s
  idle_timeout: 60s
  user: "user"
  password: "password"